"""Initial migration

Revision ID: 8d7b06ceeabd
Revises: 
Create Date: 2024-06-23 12:49:35.074633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7b06ceeabd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_result', schema=None) as batch_op:
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
